baseURL = 'https://rahulkrrrishna.xyz/'
languageCode = 'en-us'
title = 'Rahul Krrishna'
theme = 'hugo-coder'
defaultcontentlanguage = "en"
publishDir = "docs"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[pagination]
pagerSize = 20


[markup.highlight]
style = "github-dark"

[params]
  author = "Rahul Krrishna"
  info = "Frontend Engineer"
  description = "Rahul Krrishna's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "/images/dp.jpg"
  #gravatar = "rkbalu524@gmail.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/rahulakrishna/"
[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/rahulkrrrishna/"
[[params.social]]
  name = "Mastodon"
  icon = "fa-brands fa-mastodon fa-2x"
  weight = 5
  url = "https://mastodon.social/@_thisdot"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 7
  url = "https://www.linkedin.com/in/rahul-krishna-027a6438/"
[[params.social]]
  name = "Threads"
  icon = "fa-brands fa-threads fa-2x"
  weight = 9
  url = "https://www.threads.com/@rahulkrrrishna"
[[params.social]]
  name = "Bluesky"
  icon = "fa-brands fa-bluesky fa-2x"
  weight = 11
  url = "https://bsky.app/profile/rahulkrrrishna.xyz"
[[params.social]]
  name = "RSS"
  icon = "fa-solid fa-rss fa-2x"
  weight = 13
  url = "/index.xml"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "blog/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
[[menu.main]]
  name = "Resume"
  weight = 2
  url = "resume/"

